package hu.datavault.repository

import hu.datavault.model.Nationality
import org.springframework.stereotype.Repository

@Repository
class NationalityRepository {

    fun findAll(): List<Nationality> {
        return listOf(
            Nationality(countryName = "Afghanistan", alpha3Code = "AFG"),
            Nationality(countryName = "Åland Islands", alpha3Code = "ALA"),
            Nationality(countryName = "Albania", alpha3Code = "ALB"),
            Nationality(countryName = "Algeria", alpha3Code = "DZA"),
            Nationality(countryName = "American Samoa", alpha3Code = "ASM"),
            Nationality(countryName = "Andorra", alpha3Code = "AND"),
            Nationality(countryName = "Angola", alpha3Code = "AGO"),
            Nationality(countryName = "Anguilla", alpha3Code = "AIA"),
            Nationality(countryName = "Antarctica", alpha3Code = "ATA"),
            Nationality(countryName = "Antigua and Barbuda", alpha3Code = "ATG"),
            Nationality(countryName = "Argentina", alpha3Code = "ARG"),
            Nationality(countryName = "Armenia", alpha3Code = "ARM"),
            Nationality(countryName = "Aruba", alpha3Code = "ABW"),
            Nationality(countryName = "Australia", alpha3Code = "AUS"),
            Nationality(countryName = "Austria", alpha3Code = "AUT"),
            Nationality(countryName = "Azerbaijan", alpha3Code = "AZE"),
            Nationality(countryName = "Bahamas", alpha3Code = "BHS"),
            Nationality(countryName = "Bahrain", alpha3Code = "BHR"),
            Nationality(countryName = "Bangladesh", alpha3Code = "BGD"),
            Nationality(countryName = "Barbados", alpha3Code = "BRB"),
            Nationality(countryName = "Belarus", alpha3Code = "BLR"),
            Nationality(countryName = "Belgium", alpha3Code = "BEL"),
            Nationality(countryName = "Belize", alpha3Code = "BLZ"),
            Nationality(countryName = "Benin", alpha3Code = "BEN"),
            Nationality(countryName = "Bermuda", alpha3Code = "BMU"),
            Nationality(countryName = "Bhutan", alpha3Code = "BTN"),
            Nationality(countryName = "Bolivia", alpha3Code = "BOL"),
            Nationality(countryName = "Bonaire", alpha3Code = "BES"),
            Nationality(countryName = "Bosnia and Herzegovina", alpha3Code = "BIH"),
            Nationality(countryName = "Botswana", alpha3Code = "BWA"),
            Nationality(countryName = "Bouvet Island", alpha3Code = "BVT"),
            Nationality(countryName = "Brazil", alpha3Code = "BRA"),
            Nationality(countryName = "British Indian Ocean Territory", alpha3Code = "IOT"),
            Nationality(countryName = "Brunei", alpha3Code = "BRN"),
            Nationality(countryName = "Bulgaria", alpha3Code = "BGR"),
            Nationality(countryName = "Burkina Faso", alpha3Code = "BFA"),
            Nationality(countryName = "Burundi", alpha3Code = "BDI"),
            Nationality(countryName = "Cabo Verde", alpha3Code = "CPV"),
            Nationality(countryName = "Cambodia", alpha3Code = "KHM"),
            Nationality(countryName = "Cameroon", alpha3Code = "CMR"),
            Nationality(countryName = "Canada", alpha3Code = "CAN"),
            Nationality(countryName = "Cayman Islands", alpha3Code = "CYM"),
            Nationality(countryName = "Central African Republic", alpha3Code = "CAF"),
            Nationality(countryName = "Chad", alpha3Code = "TCD"),
            Nationality(countryName = "Chile", alpha3Code = "CHL"),
            Nationality(countryName = "China", alpha3Code = "CHN"),
            Nationality(countryName = "Christmas Island", alpha3Code = "CXR"),
            Nationality(countryName = "Cocos Islands", alpha3Code = "CCK"),
            Nationality(countryName = "Colombia", alpha3Code = "COL"),
            Nationality(countryName = "Comoros", alpha3Code = "COM"),
            Nationality(countryName = "Congo", alpha3Code = "COG"),
            Nationality(countryName = "Democratic Republic of the Congo", alpha3Code = "COD"),
            Nationality(countryName = "Cook Islands", alpha3Code = "COK"),
            Nationality(countryName = "Costa Rica", alpha3Code = "CRI"),
            Nationality(countryName = "Côte d'Ivoire", alpha3Code = "CIV"),
            Nationality(countryName = "Croatia", alpha3Code = "HRV"),
            Nationality(countryName = "Cuba", alpha3Code = "CUB"),
            Nationality(countryName = "Curaçao", alpha3Code = "CUW"),
            Nationality(countryName = "Cyprus", alpha3Code = "CYP"),
            Nationality(countryName = "Czechia", alpha3Code = "CZE"),
            Nationality(countryName = "Denmark", alpha3Code = "DNK"),
            Nationality(countryName = "Djibouti", alpha3Code = "DJI"),
            Nationality(countryName = "Dominica", alpha3Code = "DMA"),
            Nationality(countryName = "Dominican Republic", alpha3Code = "DOM"),
            Nationality(countryName = "Ecuador", alpha3Code = "ECU"),
            Nationality(countryName = "Egypt", alpha3Code = "EGY"),
            Nationality(countryName = "El Salvador", alpha3Code = "SLV"),
            Nationality(countryName = "Equatorial Guinea", alpha3Code = "GNQ"),
            Nationality(countryName = "Eritrea", alpha3Code = "ERI"),
            Nationality(countryName = "Estonia", alpha3Code = "EST"),
            Nationality(countryName = "Eswatini", alpha3Code = "SWZ"),
            Nationality(countryName = "Ethiopia", alpha3Code = "ETH"),
            Nationality(countryName = "Falkland Islands", alpha3Code = "FLK"),
            Nationality(countryName = "Faroe Islands", alpha3Code = "FRO"),
            Nationality(countryName = "Fiji", alpha3Code = "FJI"),
            Nationality(countryName = "Finland", alpha3Code = "FIN"),
            Nationality(countryName = "France", alpha3Code = "FRA"),
            Nationality(countryName = "French Guiana", alpha3Code = "GUF"),
            Nationality(countryName = "French Polynesia", alpha3Code = "PYF"),
            Nationality(countryName = "French Southern Territories", alpha3Code = "ATF"),
            Nationality(countryName = "Gabon", alpha3Code = "GAB"),
            Nationality(countryName = "Gambia", alpha3Code = "GMB"),
            Nationality(countryName = "Georgia", alpha3Code = "GEO"),
            Nationality(countryName = "Germany", alpha3Code = "DEU"),
            Nationality(countryName = "Ghana", alpha3Code = "GHA"),
            Nationality(countryName = "Gibraltar", alpha3Code = "GIB"),
            Nationality(countryName = "Greece", alpha3Code = "GRC"),
            Nationality(countryName = "Greenland", alpha3Code = "GRL"),
            Nationality(countryName = "Grenada", alpha3Code = "GRD"),
            Nationality(countryName = "Guadeloupe", alpha3Code = "GLP"),
            Nationality(countryName = "Guam", alpha3Code = "GUM"),
            Nationality(countryName = "Guatemala", alpha3Code = "GTM"),
            Nationality(countryName = "Guernsey", alpha3Code = "GGY"),
            Nationality(countryName = "Guinea", alpha3Code = "GIN"),
            Nationality(countryName = "Guinea-Bissau", alpha3Code = "GNB"),
            Nationality(countryName = "Guyana", alpha3Code = "GUY"),
            Nationality(countryName = "Haiti", alpha3Code = "HTI"),
            Nationality(countryName = "Heard Island and McDonald Islands", alpha3Code = "HMD"),
            Nationality(countryName = "Holy See", alpha3Code = "VAT"),
            Nationality(countryName = "Honduras", alpha3Code = "HND"),
            Nationality(countryName = "Hong Kong", alpha3Code = "HKG"),
            Nationality(countryName = "Hungary", alpha3Code = "HUN"),
            Nationality(countryName = "Iceland", alpha3Code = "ISL"),
            Nationality(countryName = "India", alpha3Code = "IND"),
            Nationality(countryName = "Indonesia", alpha3Code = "IDN"),
            Nationality(countryName = "Iran", alpha3Code = "IRN"),
            Nationality(countryName = "Iraq", alpha3Code = "IRQ"),
            Nationality(countryName = "Ireland", alpha3Code = "IRL"),
            Nationality(countryName = "Isle of Man", alpha3Code = "IMN"),
            Nationality(countryName = "Israel", alpha3Code = "ISR"),
            Nationality(countryName = "Italy", alpha3Code = "ITA"),
            Nationality(countryName = "Jamaica", alpha3Code = "JAM"),
            Nationality(countryName = "Japan", alpha3Code = "JPN"),
            Nationality(countryName = "Jersey", alpha3Code = "JEY"),
            Nationality(countryName = "Jordan", alpha3Code = "JOR"),
            Nationality(countryName = "Kazakhstan", alpha3Code = "KAZ"),
            Nationality(countryName = "Kenya", alpha3Code = "KEN"),
            Nationality(countryName = "Kiribati", alpha3Code = "KIR"),
            Nationality(countryName = "North-Korea", alpha3Code = "PRK"),
            Nationality(countryName = "South-Korea", alpha3Code = "KOR"),
            Nationality(countryName = "Kuwait", alpha3Code = "KWT"),
            Nationality(countryName = "Kyrgyzstan", alpha3Code = "KGZ"),
            Nationality(countryName = "Laos", alpha3Code = "LAO"),
            Nationality(countryName = "Latvia", alpha3Code = "LVA"),
            Nationality(countryName = "Lebanon", alpha3Code = "LBN"),
            Nationality(countryName = "Lesotho", alpha3Code = "LSO"),
            Nationality(countryName = "Liberia", alpha3Code = "LBR"),
            Nationality(countryName = "Libya", alpha3Code = "LBY"),
            Nationality(countryName = "Liechtenstein", alpha3Code = "LIE"),
            Nationality(countryName = "Lithuania", alpha3Code = "LTU"),
            Nationality(countryName = "Luxembourg", alpha3Code = "LUX"),
            Nationality(countryName = "Macao", alpha3Code = "MAC"),
            Nationality(countryName = "Madagascar", alpha3Code = "MDG"),
            Nationality(countryName = "Malawi", alpha3Code = "MWI"),
            Nationality(countryName = "Malaysia", alpha3Code = "MYS"),
            Nationality(countryName = "Maldives", alpha3Code = "MDV"),
            Nationality(countryName = "Mali", alpha3Code = "MLI"),
            Nationality(countryName = "Malta", alpha3Code = "MLT"),
            Nationality(countryName = "Marshall Islands", alpha3Code = "MHL"),
            Nationality(countryName = "Martinique", alpha3Code = "MTQ"),
            Nationality(countryName = "Mauritania", alpha3Code = "MRT"),
            Nationality(countryName = "Mauritius", alpha3Code = "MUS"),
            Nationality(countryName = "Mayotte", alpha3Code = "MYT"),
            Nationality(countryName = "Mexico", alpha3Code = "MEX"),
            Nationality(countryName = "Micronesia", alpha3Code = "FSM"),
            Nationality(countryName = "Moldova", alpha3Code = "MDA"),
            Nationality(countryName = "Monaco", alpha3Code = "MCO"),
            Nationality(countryName = "Mongolia", alpha3Code = "MNG"),
            Nationality(countryName = "Montenegro", alpha3Code = "MNE"),
            Nationality(countryName = "Montserrat", alpha3Code = "MSR"),
            Nationality(countryName = "Morocco", alpha3Code = "MAR"),
            Nationality(countryName = "Mozambique", alpha3Code = "MOZ"),
            Nationality(countryName = "Myanmar", alpha3Code = "MMR"),
            Nationality(countryName = "Namibia", alpha3Code = "NAM"),
            Nationality(countryName = "Nauru", alpha3Code = "NRU"),
            Nationality(countryName = "Nepal", alpha3Code = "NPL"),
            Nationality(countryName = "Netherlands", alpha3Code = "NLD"),
            Nationality(countryName = "New Caledonia", alpha3Code = "NCL"),
            Nationality(countryName = "New Zealand", alpha3Code = "NZL"),
            Nationality(countryName = "Nicaragua", alpha3Code = "NIC"),
            Nationality(countryName = "Niger", alpha3Code = "NER"),
            Nationality(countryName = "Nigeria", alpha3Code = "NGA"),
            Nationality(countryName = "Niue", alpha3Code = "NIU"),
            Nationality(countryName = "Norfolk Island", alpha3Code = "NFK"),
            Nationality(countryName = "North Macedonia", alpha3Code = "MKD"),
            Nationality(countryName = "Northern Mariana Islands", alpha3Code = "MNP"),
            Nationality(countryName = "Norway", alpha3Code = "NOR"),
            Nationality(countryName = "Oman", alpha3Code = "OMN"),
            Nationality(countryName = "Pakistan", alpha3Code = "PAK"),
            Nationality(countryName = "Palau", alpha3Code = "PLW"),
            Nationality(countryName = "Palestine", alpha3Code = "PSE"),
            Nationality(countryName = "Panama", alpha3Code = "PAN"),
            Nationality(countryName = "Papua New Guinea", alpha3Code = "PNG"),
            Nationality(countryName = "Paraguay", alpha3Code = "PRY"),
            Nationality(countryName = "Peru", alpha3Code = "PER"),
            Nationality(countryName = "Philippines", alpha3Code = "PHL"),
            Nationality(countryName = "Pitcairn", alpha3Code = "PCN"),
            Nationality(countryName = "Poland", alpha3Code = "POL"),
            Nationality(countryName = "Portugal", alpha3Code = "PRT"),
            Nationality(countryName = "Puerto Rico", alpha3Code = "PRI"),
            Nationality(countryName = "Qatar", alpha3Code = "QAT"),
            Nationality(countryName = "Réunion", alpha3Code = "REU"),
            Nationality(countryName = "Romania", alpha3Code = "ROU"),
            Nationality(countryName = "Russia", alpha3Code = "RUS"),
            Nationality(countryName = "Rwanda", alpha3Code = "RWA"),
            Nationality(countryName = "Saint Barthélemy", alpha3Code = "BLM"),
            Nationality(countryName = "Saint Helena", alpha3Code = "SHN"),
            Nationality(countryName = "Saint Kitts and Nevis", alpha3Code = "KNA"),
            Nationality(countryName = "Saint Lucia", alpha3Code = "LCA"),
            Nationality(countryName = "Saint Martin", alpha3Code = "MAF"),
            Nationality(countryName = "Saint Pierre and Miquelon", alpha3Code = "SPM"),
            Nationality(countryName = "Saint Vincent and the Grenadines", alpha3Code = "VCT"),
            Nationality(countryName = "Samoa", alpha3Code = "WSM"),
            Nationality(countryName = "San Marino", alpha3Code = "SMR"),
            Nationality(countryName = "Sao Tome and Principe", alpha3Code = "STP"),
            Nationality(countryName = "Saudi Arabia", alpha3Code = "SAU"),
            Nationality(countryName = "Senegal", alpha3Code = "SEN"),
            Nationality(countryName = "Serbia", alpha3Code = "SRB"),
            Nationality(countryName = "Seychelles", alpha3Code = "SYC"),
            Nationality(countryName = "Sierra Leone", alpha3Code = "SLE"),
            Nationality(countryName = "Singapore", alpha3Code = "SGP"),
            Nationality(countryName = "Sint Maarten", alpha3Code = "SXM"),
            Nationality(countryName = "Slovakia", alpha3Code = "SVK"),
            Nationality(countryName = "Slovenia", alpha3Code = "SVN"),
            Nationality(countryName = "Solomon Islands", alpha3Code = "SLB"),
            Nationality(countryName = "Somalia", alpha3Code = "SOM"),
            Nationality(countryName = "South Africa", alpha3Code = "ZAF"),
            Nationality(countryName = "South Georgia and the South Sandwich Islands", alpha3Code = "SGS"),
            Nationality(countryName = "South Sudan", alpha3Code = "SSD"),
            Nationality(countryName = "Spain", alpha3Code = "ESP"),
            Nationality(countryName = "Sri Lanka", alpha3Code = "LKA"),
            Nationality(countryName = "Sudan", alpha3Code = "SDN"),
            Nationality(countryName = "Suriname", alpha3Code = "SUR"),
            Nationality(countryName = "Svalbard and Jan Mayen", alpha3Code = "SJM"),
            Nationality(countryName = "Sweden", alpha3Code = "SWE"),
            Nationality(countryName = "Switzerland", alpha3Code = "CHE"),
            Nationality(countryName = "Syria", alpha3Code = "SYR"),
            Nationality(countryName = "Taiwan", alpha3Code = "TWN"),
            Nationality(countryName = "Tajikistan", alpha3Code = "TJK"),
            Nationality(countryName = "Tanzania", alpha3Code = "TZA"),
            Nationality(countryName = "Thailand", alpha3Code = "THA"),
            Nationality(countryName = "Timor-Leste", alpha3Code = "TLS"),
            Nationality(countryName = "Togo", alpha3Code = "TGO"),
            Nationality(countryName = "Tokelau", alpha3Code = "TKL"),
            Nationality(countryName = "Tonga", alpha3Code = "TON"),
            Nationality(countryName = "Trinidad and Tobago", alpha3Code = "TTO"),
            Nationality(countryName = "Tunisia", alpha3Code = "TUN"),
            Nationality(countryName = "Turkey", alpha3Code = "TUR"),
            Nationality(countryName = "Turkmenistan", alpha3Code = "TKM"),
            Nationality(countryName = "Turks and Caicos Islands", alpha3Code = "TCA"),
            Nationality(countryName = "Tuvalu", alpha3Code = "TUV"),
            Nationality(countryName = "Uganda", alpha3Code = "UGA"),
            Nationality(countryName = "Ukraine", alpha3Code = "UKR"),
            Nationality(countryName = "United Arab Emirates", alpha3Code = "ARE"),
            Nationality(countryName = "United Kingdom of Great Britain and Northern Ireland", alpha3Code = "GBR"),
            Nationality(countryName = "United States of America", alpha3Code = "USA"),
            Nationality(countryName = "United States Minor Outlying Islands", alpha3Code = "UMI"),
            Nationality(countryName = "Uruguay", alpha3Code = "URY"),
            Nationality(countryName = "Uzbekistan", alpha3Code = "UZB"),
            Nationality(countryName = "Vanuatu", alpha3Code = "VUT"),
            Nationality(countryName = "Venezuela", alpha3Code = "VEN"),
            Nationality(countryName = "Vietnam", alpha3Code = "VNM"),
            Nationality(countryName = "Virgin Islands (British)", alpha3Code = "VGB"),
            Nationality(countryName = "Virgin Islands (U.S.)", alpha3Code = "VIR"),
            Nationality(countryName = "Wallis and Futuna", alpha3Code = "WLF"),
            Nationality(countryName = "Western Sahara", alpha3Code = "ESH"),
            Nationality(countryName = "Yemen", alpha3Code = "YEM"),
            Nationality(countryName = "Zambia", alpha3Code = "ZMB"),
            Nationality(countryName = "Zimbabwe", alpha3Code = "ZWE"),
        )
    }
}
